// kubesage-frontend/src/app/register/page.tsx
"use client";

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Container, Row, Col, Card, Form, Button, Alert } from 'react-bootstrap';
import Link from 'next/link';
import { userService } from '../../lib/api';

export default function RegisterPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: '',
    first_name: '',
    last_name: ''
  });
  
  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };
  
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    
    // Basic validation
    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    
    if (formData.password.length < 8) {
      setError('Password must be at least 8 characters');
      return;
    }
    
    setIsLoading(true);
    try {
      const userData = {
        username: formData.username,
        email: formData.email,
        password: formData.password,
        first_name: formData.first_name,
        last_name: formData.last_name,
        is_active: true,
        is_admin: false
      };
      
      await userService.register(userData);
      router.push('/login?registered=true');
    } catch (err) {
      console.error('Registration error:', err);
      setError(err.response?.data?.detail || 'Failed to register. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };
  
  return (
    <Container className="py-5">
      <Row className="justify-content-center">
        <Col md={6}>
          <Card>
            <Card.Body className="p-4">
              <h2 className="text-center mb-4">Create an Account</h2>
              
              {error && <Alert variant="danger">{error}</Alert>}
              
              <Form onSubmit={handleSubmit}>
                <Row>
                  <Col md={6}>
                    <Form.Group className="mb-3">
                      <Form.Label>First Name</Form.Label>
                      <Form.Control
                        type="text"
                        name="first_name"
                        value={formData.first_name}
                        onChange={handleChange}
                        required
                      />
                    </Form.Group>
                  </Col>
                  <Col md={6}>
                    <Form.Group className="mb-3">
                      <Form.Label>Last Name</Form.Label>
                      <Form.Control
                        type="text"
                        name="last_name"
                        value={formData.last_name}
                        onChange={handleChange}
                        required
                      />
                    </Form.Group>
                  </Col>
                </Row>
                
                <Form.Group className="mb-3">
                  <Form.Label>Username</Form.Label>
                  <Form.Control
                    type="text"
                    name="username"
                    value={formData.username}
                    onChange={handleChange}
                    required
                  />
                </Form.Group>
                
                <Form.Group className="mb-3">
                  <Form.Label>Email</Form.Label>
                  <Form.Control
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    required
                  />
                </Form.Group>
                
                <Form.Group className="mb-3">
                  <Form.Label>Password</Form.Label>
                  <Form.Control
                    type="password"
                    name="password"
                    value={formData.password}
                    onChange={handleChange}
                    required
                    minLength={8}
                  />
                  <Form.Text className="text-muted">
                    Must be at least 8 characters long
                  </Form.Text>
                </Form.Group>
                
                <Form.Group className="mb-4">
                  <Form.Label>Confirm Password</Form.Label>
                  <Form.Control
                    type="password"
                    name="confirmPassword"
                    value={formData.confirmPassword}
                    onChange={handleChange}
                    required
                  />
                </Form.Group>
                
                <div className="d-grid">
                  <Button 
                    variant="primary" 
                    type="submit"
                    disabled={isLoading}
                  >
                    {isLoading ? 'Creating Account...' : 'Create Account'}
                  </Button>
                </div>
              </Form>
              
              <div className="text-center mt-3">
                <p>
                  Already have an account?{' '}
                  <Link href="/login">Log In</Link>
                </p>
              </div>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
}

// frontend/src/auth/register.vue
<template>
    <div class="register-container">
        <n-card title="Create an Account" bordered class="register-card">
            <n-form ref="formRef" :model="form" :rules="rules">
                <n-form-item label="Username" path="username">
                    <n-input v-model:value="form.username" placeholder="Enter your username" clearable />
                </n-form-item>

                <n-form-item label="Email" path="email">
                    <n-input v-model:value="form.email" type="email" placeholder="Enter your email" clearable />
                </n-form-item>

                <n-form-item label="Password" path="password">
                    <n-input v-model:value="form.password" type="password" placeholder="Enter your password"
                        show-password-on="click" clearable />
                </n-form-item>

                <n-form-item label="First Name" path="first_name">
                    <n-input v-model:value="form.first_name" placeholder="Enter your first name" clearable />
                </n-form-item>

                <n-form-item label="Last Name" path="last_name">
                    <n-input v-model:value="form.last_name" placeholder="Enter your last name" clearable />
                </n-form-item>

                <n-space justify="space-between">
                    <n-checkbox v-model:checked="form.is_active">Active</n-checkbox>
                    <n-checkbox v-model:checked="form.is_admin">Admin</n-checkbox>
                </n-space>

                <n-button type="primary" block :loading="loading" @click="registerUser">
                    Register
                </n-button>

                <div class="login-redirect">
                    <span>You want to login? </span>
                    <a @click="goToLogin" style="color: #409eff; cursor: pointer;">Click here</a>
                </div>
            </n-form>
        </n-card>
    </div>
</template>

<script setup>
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useMessage } from "naive-ui";
import axios from "axios";

const formRef = ref(null);
const message = useMessage();
const router = useRouter();

const form = ref({
    username: "",
    email: "",
    password: "",
    first_name: "",
    last_name: "",
    is_active: true,
    is_admin: false,
});

const loading = ref(false);

const rules = {
    username: [
        { required: true, message: "Username is required", trigger: "blur" },
        { min: 3, message: "Username must be at least 3 characters", trigger: "blur" },
    ],
    email: [
        { required: true, message: "Email is required", trigger: "blur" },
        { type: "email", message: "Invalid email format", trigger: "blur" },
    ],
    password: [
        { required: true, message: "Password is required", trigger: "blur" },
        { min: 6, message: "Password must be at least 6 characters", trigger: "blur" },
    ],
    first_name: [{ required: true, message: "First name is required", trigger: "blur" }],
    last_name: [{ required: true, message: "Last name is required", trigger: "blur" }],
};

const registerUser = async () => {
    formRef.value?.validate(async (errors) => {
        if (!errors) {
            loading.value = true;
            console.log(form.value);

            try {
                const response = await axios.post("https://10.0.34.129:8006/auth/register", form.value, {
                    headers: {
                        'Content-Type': 'application/json',
                    },
                });

                console.log(response.data);
                message.success(`User ${response.data.username} registered successfully!`);
                router.push({ name: "login" });
            } catch (error) {
                console.error(error);
                const errorMessage = error.response?.data?.detail || error.message || "Registration failed";
                message.error(errorMessage);
            } finally {
                loading.value = false;
            }
        }
    });
};

const goToLogin = () => {
    router.push({ name: "login" });
};
</script>

<style scoped>
.register-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background: #f4f4f4;
}

.register-card {
    width: 400px;
    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
}

.login-redirect {
    text-align: center;
    margin-top: 20px;
}
</style>
